import { createFileRoute, Link } from "@tanstack/react-router";
import { useEffect, useState } from "react";
import { ArrowLeft, ArrowRight, Check, ChevronLeft, ChevronRight, CircleHelp, Download, Ellipsis, Images, LockKeyhole, Mic, Music2, Pause, Play, Plus, Radio, RotateCcw, Settings2, Sparkles, X } from "lucide-react";
import { toast } from "sonner";
import { Button } from "@/components/ui/button";
import couple from "@/assets/memory-couple.jpg";
import { KeepPlayer, memoryImages, memoryLabels } from "@/components/keep-player";

export const Route = createFileRoute("/")({
  head: () => ({ meta: [
    { title: "KEEP — Say what matters. Keep it forever." },
    { name: "description", content: "Create a personal memory-film from your words, your voice, and the moments worth keeping." },
    { property: "og:title", content: "KEEP — Say what matters. Keep it forever." },
    { property: "og:description", content: "Create a personal memory-film from your words, your voice, and the moments worth keeping." },
    { property: "og:type", content: "website" },
    { name: "twitter:card", content: "summary_large_image" },
  ] }),
  component: KeepApp,
});

type Screen = "home" | "you" | "detail" | "recipient" | "occasion" | "path" | "interview" | "summary" | "message" | "record" | "recorded" | "memories" | "generating" | "editor" | "preview" | "card" | "success";
type Mode = "Memories" | "Music" | "Captions" | "Style";
const occasions = ["Birthday", "Anniversary", "Wedding", "New Baby", "Mother's Day", "Father's Day", "Graduation", "Thank You", "Just Because", "Other"];
const relationships = ["Spouse", "Mom", "Dad", "Child", "Grandparent", "Friend", "Someone else"];
const questions = [
  "Tell me about Hanna. Who is she to you beyond just being your wife?",
  "You said she makes people feel at home. Can you remember a specific moment when you really noticed that?",
  "What are the little ordinary things about her that you never want to forget?",
  "How has your life changed watching her become a mom?",
  "When you picture the two of you twenty years from now, what do you hope she knows?",
];
const answers = [
  "She's my best friend. She's my sounding board, my encourager, and the person who believes in me when I don't believe in myself.",
  "At our first dinner with friends, she noticed someone was quiet and made room for them. By the end of the night, they felt like family.",
  "The way she hums while she makes coffee. How she reaches for my hand without thinking. How she remembers what everyone needs.",
  "Then I got to watch her become a mom, and somehow my love for her found a whole new shape.",
  "I hope she knows that through all the changes, I would choose this life with her again. Every time.",
];
const initialMessage = [
  "Hanna, I wanted to make this because there are so many things that I think about you and appreciate about you that I probably don't say enough.",
  "You're my best friend. You're my sounding board. You're my encourager. You're the person who believes in me when I don't believe in myself.",
  "One of the things I notice most is the way you make people feel. You have this ability to make people feel seen and known and heard and loved. You make people feel at home.",
  "And then I got to watch you become a mom. In the smallest, most ordinary moments, I see the life we've made together and I can't believe I get to share it with you.",
  "Twenty years from now, I hope you know this: through every version of us, I'd choose this life with you again. Always.",
];
const tracks = [
  { name: "Warm + Nostalgic", note: "Soft piano, golden-hour feeling", group: "For You" },
  { name: "Joyful", note: "Lighthearted and full of life", group: "For You" },
  { name: "Cinematic", note: "A story that stays with you", group: "For You" },
  { name: "Romantic", note: "Tender, close, timeless", group: "More feelings" },
  { name: "Hopeful", note: "A little light ahead", group: "More feelings" },
  { name: "Playful", note: "For the memories that make you smile", group: "More feelings" },
  { name: "Reflective", note: "Quiet and thoughtful", group: "More feelings" },
  { name: "Acoustic", note: "Warm strings and open air", group: "More feelings" },
  { name: "Piano", note: "Just the keys and your words", group: "More feelings" },
];
const captionOptions = ["Clean", "Reel", "Film", "Story", "Minimal", "None"];
const styles = [{name:"Natural", note:"Clean, subtle movement"}, {name:"Warm", note:"Gentle warmth, soft dissolves"}, {name:"Film", note:"Cinematic grain, slower movement"}, {name:"Modern", note:"Crisp movement, contemporary type"}];

function KeepApp() {
  const [screen, setScreen] = useState<Screen>("home");
  const [history, setHistory] = useState<Screen[]>([]);
  const [relationship, setRelationship] = useState("");
  const [name, setName] = useState("Hanna");
  const [occasion, setOccasion] = useState("Anniversary");
  const [question, setQuestion] = useState(0);
  const [answered, setAnswered] = useState(false);
  const [message, setMessage] = useState(initialMessage);
  const [activeParagraph, setActiveParagraph] = useState(0);
  const [askOpen, setAskOpen] = useState(false);
  const [recording, setRecording] = useState(false);
  const [paused, setPaused] = useState(false);
  const [seconds, setSeconds] = useState(0);
  const [added, setAdded] = useState(false);
  const [generation, setGeneration] = useState(0);
  const [mode, setMode] = useState<Mode>("Memories");
  const [frames, setFrames] = useState(memoryImages);
  const [frame, setFrame] = useState(0);
  const [duration, setDuration] = useState(4);
  const [music, setMusic] = useState("Warm + Nostalgic");
  const [balance, setBalance] = useState("Balanced");
  const [caption, setCaption] = useState("Reel");
  const [style, setStyle] = useState("Natural");
  const [editorPlaying, setEditorPlaying] = useState(true);
  const [engraving, setEngraving] = useState(["HANNA", "FROM ALEX", "2026"]);
  const [cardBack, setCardBack] = useState(false);
  const [finished, setFinished] = useState(false);
  const [setting, setSetting] = useState("");
  const go = (next: Screen) => { setHistory(h => [...h, screen]); setScreen(next); window.scrollTo(0, 0); };
  const back = () => { const last = history[history.length - 1]; setScreen(last ?? "home"); setHistory(h => h.slice(0,-1)); window.scrollTo(0,0); };
  const begin = () => { setHistory([screen]); setScreen("recipient"); window.scrollTo(0,0); };
  useEffect(() => { if (!recording || paused) return; const t = window.setInterval(() => setSeconds(s => s + 1), 1000); return () => window.clearInterval(t); }, [recording, paused]);
  useEffect(() => { if (screen !== "generating") return; if (generation >= 3) { const t = window.setTimeout(() => go("editor"), 650); return () => window.clearTimeout(t); } const t = window.setTimeout(() => setGeneration(n => n + 1), 1250); return () => window.clearTimeout(t); }, [screen, generation]);
  useEffect(() => { if (screen !== "editor" || !editorPlaying || frames.length < 2) return; const t = window.setInterval(() => setFrame(i => (i + 1) % frames.length), 4200); return () => window.clearInterval(t); }, [screen, editorPlaying, frames.length]);
  const selectedImage = frames[frame % frames.length] ?? couple;
  const updateEngraving = (i: number, value: string) => setEngraving(old => old.map((v, j) => j === i ? value.toUpperCase() : v));
  const title = (eyebrow: string, heading: string, sub?: string) => <div className="mb-8"><p className="eyebrow mb-5">{eyebrow}</p><h1 className="display text-[clamp(48px,13vw,70px)]">{heading}</h1>{sub && <p className="mt-5 text-sm leading-6 text-muted-foreground">{sub}</p>}</div>;
  const top = (label?: string) => <header className="flex h-20 items-center justify-between px-6 pt-3"><Button variant="bare" size="icon" aria-label="Go back" onClick={back}><ArrowLeft /></Button><span className="brand text-base">KEEP</span><span className="min-w-9 text-right text-[10px] tracking-widest text-muted-foreground">{label}</span></header>;
  const nextButton = (label: string, action: () => void, disabled = false) => <Button variant="keep" size="touch" className="w-full justify-between" onClick={action} disabled={disabled}>{label}<ArrowRight /></Button>;
  const wave = (count = 27) => <div className="flex h-12 items-center justify-center gap-[3px]" aria-hidden="true">{Array.from({length:count}, (_,i) => <span key={i} className="wave-bar w-[2px] rounded-full bg-accent" style={{height: `${10 + ((i * 17) % 34)}px`, animationDelay: `${-(i % 7) * .13}s`}} />)}</div>;
  const primaryNav = screen === "home" || screen === "you";
  const isFull = screen === "interview" || screen === "record" || screen === "preview" || screen === "generating";

  return <main className="app-shell"><div key={screen} className={`page-enter ${primaryNav ? "pb-28" : ""}`}>
    {screen === "home" && <>
      <header className="flex items-center justify-between px-7 pb-8 pt-10"><span className="brand">KEEP</span><Button variant="bare" size="icon" aria-label="Profile" onClick={() => go("you")}><span className="flex size-9 items-center justify-center rounded-full border border-border text-xs">A</span></Button></header>
      <div className="px-7">{title("The things we hold onto", "Say what matters. Keep it forever.")}{nextButton("Create a Keep", begin)}<div className="mt-12 mb-5 flex items-end justify-between"><h2 className="text-sm font-medium">Your Keeps</h2><span className="text-xs text-muted-foreground">02 keeps</span></div></div>
      <Button variant="bare" className="relative mx-4 block h-[420px] w-[calc(100%-2rem)] overflow-hidden rounded-sm !p-0 text-left" onClick={() => go("detail")} aria-label="Open Hanna's Keep"><img src={memoryImages[0]} alt="Couple at the coast, illustrative prototype photograph" className="absolute inset-0 h-full w-full object-cover" /><div className="absolute inset-0 photo-bottom"/><div className="absolute bottom-0 left-0 right-0 p-6"><span className="eyebrow text-foreground">READY TO KEEP <span className="ml-2 inline-block size-1.5 rounded-full bg-accent" /></span><h3 className="display mt-4 text-6xl">HANNA</h3><div className="mt-3 flex justify-between text-xs text-foreground/80"><span>Anniversary · 2026</span><span>3:57 <ArrowRight className="ml-2 inline-block size-4" /></span></div></div></Button>
      <Button variant="bare" className="mx-4 mt-4 flex h-24 w-[calc(100%-2rem)] items-center gap-4 rounded-sm border border-border p-2 text-left" onClick={() => { toast("Draft opened"); begin(); }}><img src={memoryImages[3]} alt="Family memory placeholder" className="h-full w-20 object-cover" /><span className="flex-1"><strong className="block text-sm font-medium">Our Family</strong><small className="mt-1 block text-muted-foreground">Christmas 2026 · Draft</small></span><ChevronRight className="mr-3 size-4 text-muted-foreground" /></Button>
    </>}
    {screen === "you" && <>{top()}<div className="px-7 pt-8">{title("Your space", "Alex.", "The things worth keeping, all in one place.")}<div className="mt-12 border-t border-border">{([{label:"My cards", Icon:Radio},{label:"Downloads & backups", Icon:Download},{label:"Privacy", Icon:LockKeyhole},{label:"Help", Icon:CircleHelp}]).map(({label, Icon}) => <Button key={label} variant="bare" className="flex h-17 w-full justify-between border-b border-border px-0 text-sm font-normal" onClick={() => setSetting(label)}><span className="flex items-center gap-4"><Icon className="size-4 text-accent" />{label}</span><ChevronRight className="size-4 text-muted-foreground" /></Button>)}</div><p className="mt-9 text-xs leading-6 text-muted-foreground">Your Keeps are private by default. Only people you share them with can open them.</p></div>{setting && <div className="fixed inset-0 z-40 flex items-end justify-center bg-background/75" onClick={() => setSetting("")}><div className="w-full max-w-[540px] rounded-t-lg bg-card p-7 pb-12" onClick={e => e.stopPropagation()}><div className="flex justify-between"><h2 className="font-display text-4xl">{setting}</h2><Button variant="bare" size="icon" onClick={() => setSetting("")} aria-label="Close"><X /></Button></div><p className="mt-5 text-sm leading-7 text-muted-foreground">{setting === "Privacy" ? "Your Keeps are private by default. Sharing a card gives its recipient access to that Keep. No account is required to view it." : setting === "My cards" ? "Card #000001 · HANNA · from Alex · 2026" : setting === "Downloads & backups" ? "Your finished Keeps and recordings will appear here. This prototype does not save downloads yet." : "We're here when you need us. This is a preview of KEEP, so support is not connected yet."}</p><Button variant="quiet" className="mt-8 w-full" onClick={() => setSetting("")}>Done</Button></div></div>}</>}
    {screen === "detail" && <>{top("READY")}<div className="relative mx-4 h-[55dvh] min-h-[390px] overflow-hidden"><img src={memoryImages[0]} alt="Couple at the coast, illustrative prototype photograph" className="h-full w-full object-cover"/><div className="absolute inset-0 photo-bottom"/><div className="absolute bottom-8 left-6"><p className="eyebrow text-foreground">ANNIVERSARY · 2026</p><h1 className="display mt-3 text-7xl">HANNA</h1><p className="mt-3 text-sm">from Alex · 3:57</p></div></div><div className="space-y-3 px-6 pt-7">{nextButton("Play Keep", () => go("preview"))}<Button variant="quiet" size="touch" className="w-full" onClick={() => go("editor")}><Settings2 /> Make Changes</Button><Button variant="bare" size="touch" className="w-full" onClick={() => go("success")}><Radio /> View card details</Button></div></>}
    {screen === "recipient" && <>{top("01 / 04")}<div className="px-7 pt-12">{title("Begin with someone", "Who are you making this for?")}<div className="grid grid-cols-2 gap-2">{relationships.map(r => <Button key={r} variant={relationship === r ? "selected" : "quiet"} className="h-18 justify-between px-4 text-left font-normal" onClick={() => setRelationship(r)}>{r}{relationship === r && <Check className="size-4 text-accent" />}</Button>)}</div>{relationship && <div className="mt-9 page-enter"><label htmlFor="recipient-name" className="eyebrow">THEIR NAME</label><input id="recipient-name" value={name} onChange={e => setName(e.target.value)} placeholder="Their name" className="mt-3 w-full border-0 border-b border-border bg-transparent pb-4 font-display text-5xl outline-none focus:border-accent" /><p className="mt-3 text-xs text-muted-foreground">A name only you could say this way.</p></div>}<div className="mt-10">{nextButton("Continue", () => go("occasion"), !relationship || !name.trim())}</div></div></>}
    {screen === "occasion" && <>{top("02 / 04")}<div className="px-7 pt-12">{title("Give it a moment", "What's this Keep for?")}<div className="flex flex-wrap gap-2">{occasions.map(o => <Button key={o} variant={occasion === o ? "selected" : "quiet"} className="h-12 rounded-full px-5 font-normal" onClick={() => setOccasion(o)}>{o}</Button>)}</div><div className="mt-12">{nextButton("Continue", () => go("path"))}</div></div></>}
    {screen === "path" && <>{top("03 / 04")}<div className="px-7 pt-12">{title("The heart of it", "What do you want to say?")}<div className="space-y-3"><Button variant="quiet" className="h-auto w-full items-start justify-between gap-5 p-6 text-left whitespace-normal" onClick={() => { setQuestion(0); setAnswered(false); go("interview"); }}><span><Sparkles className="mb-7 size-6 text-accent"/><strong className="block font-display text-3xl font-normal">Help me find the words</strong><small className="mt-3 block text-sm font-normal leading-6 text-muted-foreground">KEEP will talk with you and help uncover what you really want to say.</small></span><ArrowRight className="mt-1 size-4" /></Button><Button variant="quiet" className="h-auto w-full items-start justify-between gap-5 p-6 text-left whitespace-normal" onClick={() => { setMessage(initialMessage); go("message"); }}><span><span className="mb-7 block font-display text-3xl text-accent">“</span><strong className="block font-display text-3xl font-normal">I know what I want to say</strong><small className="mt-3 block text-sm font-normal leading-6 text-muted-foreground">Write it yourself or bring in something you've already written.</small></span><ArrowRight className="mt-1 size-4" /></Button></div></div></>}
    {screen === "interview" && <div className="flex h-dvh min-h-[650px] flex-col px-7 pb-[max(30px,env(safe-area-inset-bottom))]">{top()}<div className="mt-6"><p className="eyebrow">GETTING TO KNOW YOUR STORY…</p><div className="mt-4 flex gap-1">{questions.map((_,i)=><div key={i} className={`h-[2px] flex-1 ${i <= question ? "bg-accent" : "bg-border"}`}/>)}</div></div><div className="flex flex-1 flex-col items-center justify-center text-center"><span className="mb-10 font-display text-6xl text-accent">“</span><h1 className="font-display text-[clamp(33px,8vw,47px)] leading-[1.09]">{questions[question]}</h1>{answered && <p className="mt-9 border-l border-accent pl-5 text-left text-sm leading-7 text-muted-foreground page-enter">{answers[question]}</p>}</div><div className="flex flex-col items-center gap-5">{wave()}<Button variant={answered ? "quiet" : "keep"} size="touch" className="w-full" onClick={() => { if (!answered) setAnswered(true); else if (question < questions.length-1) { setQuestion(q=>q+1); setAnswered(false); } else go("summary"); }}>{answered ? <><span>{question === questions.length-1 ? "That's everything" : "Continue"}</span><ArrowRight /></> : <><Mic /> Demo answer</>}</Button><p className="text-center text-xs text-muted-foreground">Interview responses are simulated in this prototype.</p></div></div>}
    {screen === "summary" && <>{top()}<div className="flex min-h-[calc(100dvh-100px)] flex-col justify-between px-7 pb-10 pt-15"><div>{title("Your story, in your words", "I think we have it.")}<p className="font-display text-3xl leading-snug text-foreground/90">Hanna is your closest friend, the person who believes in you, and the one who makes everyone around her feel at home.</p><p className="mt-7 text-sm leading-7 text-muted-foreground">From the quiet rituals of your everyday life to watching her become a mother, this is a story about choosing each other through every version of life.</p></div>{nextButton("Create My Message", () => go("message"))}</div></>}
    {screen === "message" && <>{top("04 / 04")}<div className="px-7 pb-32 pt-9">{title("In your own words", "Your message is ready.", "Tap any paragraph to make it yours.")}<div className="space-y-1">{message.map((p,i) => <textarea key={i} aria-label={`Message paragraph ${i+1}`} rows={Math.max(3,Math.ceil(p.length/44))} value={p} onFocus={() => setActiveParagraph(i)} onChange={e => setMessage(old => old.map((item,j) => j === i ? e.target.value : item))} className={`w-full resize-none rounded-sm border bg-transparent p-3 font-display text-[23px] leading-[1.3] outline-none transition-colors ${activeParagraph === i ? "border-accent/50" : "border-transparent"}`} />)}</div><Button variant="quiet" size="touch" className="mt-5 w-full" onClick={() => setAskOpen(true)}><Sparkles /> Ask KEEP</Button><div className="mt-3">{nextButton("Record Your Keep", () => go("record"))}</div></div>{askOpen && <div className="fixed inset-0 z-40 flex items-end justify-center bg-background/80" onClick={() => setAskOpen(false)}><div className="w-full max-w-[540px] rounded-t-lg bg-card px-7 pb-10 pt-6" onClick={e => e.stopPropagation()}><div className="flex items-center justify-between"><h2 className="font-display text-4xl">Ask KEEP</h2><Button variant="bare" size="icon" aria-label="Close" onClick={() => setAskOpen(false)}><X /></Button></div><p className="mt-2 mb-6 text-xs text-muted-foreground">For the paragraph you've selected</p>{["Make this sound more like me", "Shorten this section", "Make the ending stronger", "Add a memory"].map(prompt => <Button key={prompt} variant="bare" className="flex h-14 w-full justify-between border-t border-border px-0 font-normal" onClick={() => { setMessage(old => old.map((p,i) => i !== activeParagraph ? p : prompt === "Shorten this section" ? p.split(". ").slice(0,2).join(". ").replace(/\.?$/, ".") : prompt === "Add a memory" ? `${p} I still think of the way we laughed on that trip by the sea.` : prompt === "Make the ending stronger" ? `${p} I love you, and I always will.` : p.replace("I wanted to make this because", "I've been meaning to tell you this because"))); setAskOpen(false); toast.success("This paragraph has been updated"); }}>{prompt}<ArrowRight className="size-4 text-accent"/></Button>)}</div></div>}</>}
    {screen === "record" && <div className="relative flex h-dvh min-h-[650px] flex-col overflow-hidden px-7 pb-[max(32px,env(safe-area-inset-bottom))]">{top()}<div className="pt-6 text-center"><p className="eyebrow">YOUR VOICE, YOUR KEEP</p><h1 className="display mt-5 text-5xl">Now say it in your own voice.</h1><p className="mt-4 text-sm text-muted-foreground">These are your words. They should sound like you.</p></div><div className="script-fade my-10 flex-1 overflow-hidden"><div className={`space-y-9 text-center transition-transform duration-[8s] ease-linear ${recording && !paused ? "-translate-y-24" : "translate-y-0"}`}>{message.map((p,i)=><p key={i} className={`font-display text-3xl leading-[1.35] ${i === 0 ? "text-foreground" : "text-muted-foreground"}`}>{p}</p>)}</div></div><div className="text-center"><div className="mb-1 text-sm tabular-nums">{String(Math.floor(seconds/60)).padStart(2,"0")}:{String(seconds%60).padStart(2,"0")}</div>{wave(33)}<div className="mt-5 flex gap-2">{!recording ? <Button variant="keep" size="touch" className="w-full" onClick={() => { setRecording(true); setPaused(false); }}><Mic /> Start Recording</Button> : <><Button variant="quiet" size="touch" className="flex-1" onClick={() => setPaused(!paused)}>{paused ? <Play /> : <Pause />}{paused ? "Resume" : "Pause"}</Button><Button variant="keep" size="touch" className="flex-1" onClick={() => { setRecording(false); go("recorded"); }}><Check /> Finish</Button></>}</div><p className="mx-auto mt-5 max-w-xs text-[11px] leading-5 text-muted-foreground">KEEP will clean background noise and balance levels. Your voice stays your voice. Recording is simulated here.</p></div></div>}
    {screen === "recorded" && <>{top()}<div className="flex min-h-[calc(100dvh-90px)] flex-col justify-between px-7 pb-10 pt-18"><div>{title("A voice worth keeping", "Your voice is ready.", "Every word sounds more like you when it's said by you.")}<div className="mt-14 rounded-sm border border-border p-6">{wave(42)}<div className="mt-5 flex items-center justify-between text-xs text-muted-foreground"><span>ALEX'S RECORDING</span><span>3:57</span></div></div><Button variant="bare" size="touch" className="mt-5 w-full" onClick={() => toast("Playback is simulated in this prototype")}><Play /> Play recording</Button><Button variant="bare" size="touch" className="w-full text-muted-foreground" onClick={() => { setSeconds(0); go("record"); }}><RotateCcw /> Record again</Button></div>{nextButton("Use Recording", () => go("memories"))}</div></>}
    {screen === "memories" && <>{top()}<div className="px-7 pb-10 pt-9">{title("The moments in between", "Bring your words to life.", "Add photos & videos that belong to this story.")}{!added ? <div className="mt-10"><div className="grid h-72 grid-cols-3 gap-1 overflow-hidden opacity-60"><img className="col-span-2 h-full w-full object-cover" src={memoryImages[2]} alt="Travel memory placeholder"/><div className="flex flex-col gap-1"><img className="h-1/2 w-full object-cover" src={memoryImages[1]} alt="Wedding memory placeholder"/><img className="h-1/2 w-full object-cover" src={memoryImages[3]} alt="Family memory placeholder"/></div></div><Button variant="keep" size="touch" className="mt-8 w-full" onClick={() => setAdded(true)}><Images /> Choose Photos & Videos</Button><p className="mt-4 text-center text-xs text-muted-foreground">Tap to add 48 sample memories in this prototype.</p></div> : <div className="page-enter"><div className="grid grid-cols-4 gap-1">{Array.from({length:12},(_,i)=><div key={i} className="aspect-square overflow-hidden"><img src={memoryImages[i % memoryImages.length]} alt={`Sample memory ${i+1}`} className="h-full w-full object-cover"/></div>)}</div><p className="mt-5 text-center text-sm">48 memories added <Check className="ml-1 inline size-4 text-accent" /></p><div className="mt-10">{nextButton("Create My Keep", () => { setGeneration(0); go("generating"); })}</div><p className="mt-4 text-center text-xs text-muted-foreground">A preview sequence will be simulated.</p></div>}</div></>}
    {screen === "generating" && <div className="flex h-dvh flex-col items-center justify-center px-8 text-center"><div className="relative mb-14 flex size-30 items-center justify-center"><div className="pulse-ring absolute inset-0 rounded-full border border-accent"/><Sparkles className="size-8 text-accent" /></div><div className="eyebrow mb-5">MAKING SOMETHING THAT LASTS</div><h1 key={generation} className="display min-h-32 text-5xl page-enter">{["Listening to your story…", "Finding the moments that fit…", "Building your Keep…", "Almost there…"][generation]}</h1><p className="mt-8 text-xs text-muted-foreground">Simulated creation preview</p></div>}
    {screen === "editor" && <div className="flex h-dvh min-h-[680px] flex-col"><div className="relative min-h-0 flex-1 overflow-hidden bg-card"><img key={frame} src={selectedImage} alt={`Memory preview ${frame+1}`} className={`h-full w-full object-cover ${editorPlaying ? "ken-burns" : ""} editor-image-${style.toLowerCase()}`} /><div className="absolute inset-0 photo-shade"/><div className="absolute top-0 left-0 right-0 flex items-start justify-between px-5 pt-[max(20px,env(safe-area-inset-top))]"><Button variant="bare" size="icon" aria-label="Back" onClick={back}><ArrowLeft /></Button><div className="text-center"><strong className="block text-sm font-medium tracking-[.16em]">{name.toUpperCase()}</strong><small className="text-[10px] text-foreground/80">{occasion} · 2026</small></div><Button variant="bare" size="icon" aria-label="Preview Keep" onClick={() => go("preview")}><Play /></Button></div>{caption !== "None" && <div className="absolute bottom-18 left-6 right-6 text-center"><p className={`${caption === "Film" ? "font-display text-4xl font-normal" : caption === "Minimal" ? "text-lg" : "text-[23px] font-semibold"} leading-tight drop-shadow-md`}>{caption === "Reel" ? <>YOU MAKE PEOPLE FEEL <span className="text-accent">AT HOME</span></> : caption === "Minimal" ? "Feel at home." : "You make people feel at home."}</p></div>}<div className="absolute bottom-5 left-5 right-5 flex items-center gap-4"><Button variant="bare" size="icon" aria-label={editorPlaying ? "Pause preview" : "Play preview"} onClick={() => setEditorPlaying(!editorPlaying)}>{editorPlaying ? <Pause fill="currentColor"/> : <Play fill="currentColor"/>}</Button><div className="h-[2px] flex-1 bg-foreground/40"><div className="h-full w-1/3 bg-foreground"/></div><span className="text-[11px] tabular-nums">1:12 / 3:57</span></div></div><div className="flex max-h-[46dvh] min-h-[315px] flex-col bg-background"><div className="flex border-b border-border">{(["Memories","Music","Captions","Style"] as Mode[]).map((m,i) => { const Icon = [Images,Music2,Ellipsis,Sparkles][i] ?? Images; return <Button key={m} variant="bare" className={`flex h-15 flex-1 flex-col gap-1 rounded-none border-b-2 px-0 text-[11px] font-normal ${mode === m ? "border-accent text-foreground" : "border-transparent text-muted-foreground"}`} onClick={() => setMode(m)}><Icon className="size-4"/>{m}</Button>; })}</div><div className="thin-scroll flex-1 overflow-y-auto px-5 py-5">
      {mode === "Memories" && <><div className="mb-4 flex items-center justify-between"><h2 className="font-display text-2xl">Your moments</h2><Button variant="bare" className="text-xs text-accent" onClick={() => { setFrames([...memoryImages]); setFrame(3); toast.success("Moments matched to your story"); }}><Sparkles /> Match to my story</Button></div><div className="thin-scroll flex gap-2 overflow-x-auto pb-2">{frames.map((image,i)=><Button key={i} variant="bare" className={`relative h-20 w-16 shrink-0 overflow-hidden rounded-sm !p-0 ${i === frame ? "ring-2 ring-accent" : "opacity-65"}`} aria-label={`Select memory ${i+1}`} onClick={() => setFrame(i)}><img src={image} alt={memoryLabels[i % memoryLabels.length]} className="h-full w-full object-cover"/></Button>)}<Button variant="quiet" className="h-20 w-16 shrink-0 flex-col text-[10px]" onClick={() => { setFrames(old => [...old, (memoryImages[old.length % memoryImages.length] ?? couple)]); toast.success("Sample memory added"); }}><Plus/>Add</Button></div><p className="mt-3 text-[11px] text-muted-foreground">Matched to: “{frame === 3 || frame === 6 ? "Then I got to watch you become a mom…" : "You make people feel at home…"}”</p><div className="mt-3 flex flex-wrap items-center gap-1"><Button variant="bare" size="sm" aria-label="Move memory left" disabled={frame === 0} onClick={() => { const next=[...frames]; const current = next[frame]; const adjacent = next[frame-1]; if (!current || !adjacent) return; next[frame-1]=current; next[frame]=adjacent; setFrames(next); setFrame(frame-1); }}><ChevronLeft/> Move</Button><Button variant="bare" size="sm" aria-label="Move memory right" disabled={frame >= frames.length-1} onClick={() => { const next=[...frames]; const current = next[frame]; const adjacent = next[frame+1]; if (!current || !adjacent) return; next[frame+1]=current; next[frame]=adjacent; setFrames(next); setFrame(frame+1); }}>Move <ChevronRight/></Button><Button variant="bare" size="sm" onClick={() => { setFrames(old => old.map((x,i) => i === frame ? (memoryImages[(memoryImages.indexOf(x)+1) % memoryImages.length] ?? couple) : x)); toast("Replaced with a sample memory"); }}>Replace</Button><Button variant="bare" size="sm" disabled={frames.length <= 1} onClick={() => { setFrames(old => old.filter((_,i)=>i!==frame)); setFrame(0); }}>Remove</Button><Button variant="bare" size="sm" onClick={() => setDuration(d => d >= 8 ? 2 : d+1)}>Duration {duration}s</Button></div></>}
      {mode === "Music" && <><h2 className="font-display text-3xl">Choose a feeling.</h2>{["For You","More feelings"].map(group=><div key={group} className="mt-5"><p className="eyebrow mb-2">{group}</p>{tracks.filter(t=>t.group===group).map(track=><Button key={track.name} variant="bare" className="flex h-15 w-full justify-between border-b border-border px-0 text-left" onClick={() => { setMusic(track.name); toast(`${track.name} selected · preview only`); }}><span className="flex items-center gap-3"><span className="flex size-8 items-center justify-center rounded-full border border-border"><Play className="size-3" /></span><span><strong className="block text-xs font-medium">{track.name} {track.name === "Warm + Nostalgic" && <span className="text-accent"> · recommended</span>}</strong><small className="text-[10px] text-muted-foreground">{track.note}</small></span></span>{music === track.name && <Check className="size-4 text-accent"/>}</Button>)}</div>)}<p className="eyebrow mt-7 mb-3">VOICE / MUSIC</p><div className="flex gap-1">{["Soft","Balanced","Full"].map(b=><Button key={b} variant={balance===b ? "selected" : "quiet"} className="flex-1" onClick={()=>setBalance(b)}>{b}</Button>)}</div><p className="mt-4 text-xs leading-5 text-muted-foreground">KEEP automatically lowers music while you speak and lets it rise between moments.</p></>}
      {mode === "Captions" && <><h2 className="font-display text-3xl">How should your words appear?</h2><p className="mt-2 mb-5 text-xs text-muted-foreground">Captions are timed directly to your recording.</p><div className="grid grid-cols-2 gap-2">{captionOptions.map(c=><Button key={c} variant={caption===c ? "selected" : "quiet"} className="h-20 flex-col whitespace-normal" onClick={()=>setCaption(c)}><span className={c === "Film" ? "font-display text-xl" : "text-sm"}>{c}</span><small className="text-[10px] font-normal text-muted-foreground">{c === "None" ? "Just the image" : c === "Reel" ? "Bold, word by word" : c === "Film" ? "Elegant serif" : c === "Story" ? "Emotional phrases" : c === "Minimal" ? "Key lines only" : "Simple subtitles"}</small></Button>)}</div></>}
      {mode === "Style" && <><h2 className="font-display text-3xl">Choose the feel.</h2><div className="mt-5 grid grid-cols-2 gap-2">{styles.map(s=><Button key={s.name} variant={style===s.name ? "selected" : "quiet"} className="h-27 flex-col items-start whitespace-normal p-4 text-left" onClick={()=>setStyle(s.name)}><span className="font-display text-2xl">{s.name}</span><small className="text-[11px] font-normal leading-4 text-muted-foreground">{s.note}</small></Button>)}</div></>}
    </div><div className="border-t border-border px-5 py-3 safe-bottom">{nextButton("Preview Keep", () => go("preview"))}</div></div></div>}
    {screen === "preview" && <KeepPlayer name={name.toUpperCase()} from="Alex" year="2026" onExit={back} onFinish={() => go("card")} style={style} captions={caption} />}
    {screen === "card" && <>{top()}<div className="px-7 pb-10 pt-7">{title("The final touch", "Give it somewhere to live.", "Your card opens this Keep with a tap. No app or login required.")}<Button variant="bare" className="card-object mx-auto flex aspect-[1.586] w-full max-w-[400px] flex-col items-start justify-between rounded-lg border border-foreground/10 p-7 text-left" onClick={() => setCardBack(!cardBack)} aria-label="Flip keepsake card">{!cardBack ? <><span className="brand text-xl">KEEP</span><span className="self-end text-xs tracking-widest text-accent">◉</span></> : <><span className="brand text-sm">KEEP</span><span className="engraved flex flex-col gap-1 text-xs tracking-[.2em]"><strong className="text-xl font-normal">{engraving[0]}</strong><span>{engraving[1]}</span><span>{engraving[2]}</span></span></>}</Button><p className="mt-4 text-center text-xs text-muted-foreground">Tap card to see {cardBack ? "front" : "engraving"}</p><div className="mt-9 space-y-4">{["Name", "From", "Year"].map((label,i)=><label key={label} className="block"><span className="eyebrow">{label}</span><input aria-label={`Card ${label}`} maxLength={22} value={engraving[i]} onChange={e => updateEngraving(i,e.target.value)} onFocus={() => setCardBack(true)} className="mt-2 w-full border-0 border-b border-border bg-transparent pb-3 text-sm tracking-widest outline-none focus:border-accent"/></label>)}</div><div className="mt-10">{nextButton("Create My Keep", () => { setFinished(true); go("success"); })}</div><p className="mt-3 text-center text-[11px] text-muted-foreground">Card ordering is simulated in this prototype.</p></div></>}
    {screen === "success" && <div className="flex min-h-dvh flex-col justify-between px-7 pb-10 pt-10"><span className="brand">KEEP</span><div className="py-12"><div className="mb-10 flex size-13 items-center justify-center rounded-full border border-accent text-accent"><Check /></div>{title("Keep this version of them", "Your Keep is ready.")}<div className="card-object mt-12 aspect-[1.586] w-full rounded-lg border border-foreground/10 p-7"><span className="brand text-lg">KEEP</span><div className="mt-14 text-xs tracking-[.2em] text-accent">{engraving[0]}<br/>{engraving[1]} · {engraving[2]}</div></div><p className="mt-5 text-xs text-muted-foreground">Card #000001 · {engraving[0]} · from Alex · 2026</p>{finished && <p className="mt-3 text-xs text-muted-foreground">Your physical card has not been ordered. This is a prototype.</p>}</div><div className="space-y-3"><Button variant="keep" size="touch" className="w-full justify-between" asChild><Link to="/recipient" search={{ name: name.trim() || "Hanna", from: "Alex", year: "2026" }}>Preview recipient experience <ArrowRight /></Link></Button><Button variant="quiet" size="touch" className="w-full" onClick={() => { setHistory([]); setScreen("home"); }}>Back to Keeps</Button></div></div>}
  </div>{primaryNav && <nav aria-label="Main navigation" className="nav-bottom fixed bottom-0 left-1/2 z-20 w-full max-w-[540px] -translate-x-1/2 flex h-[82px] border-t border-border bg-background/95 backdrop-blur-xl"><Button variant="bare" className={`h-16 flex-1 flex-col gap-1 text-[11px] ${screen === "home" ? "text-accent" : "text-muted-foreground"}`} onClick={() => go("home")}><Images className="size-5"/>Keeps</Button><Button variant="bare" className="h-16 flex-1 flex-col gap-1 text-[11px] text-muted-foreground" onClick={begin}><Plus className="size-5"/>Create</Button><Button variant="bare" className={`h-16 flex-1 flex-col gap-1 text-[11px] ${screen === "you" ? "text-accent" : "text-muted-foreground"}`} onClick={() => go("you")}><span className="flex size-5 items-center justify-center rounded-full border text-[10px]">A</span>You</Button></nav>}</main>;
}
